export const GET_MATCHES = "GET_MATCHES";
export const GET_MATCHES_SUCCESS = "GET_MATCHES_SUCCESS";
export const GET_MATCHES_FAILURE = "GET_MATCHES_FAILURE";

export const GET_TODAYS_MATCHES = "GET_TODAYS_MATCHES";
export const GET_TODAYS_MATCHES_SUCCESS = "GET_TODAYS_MATCHES_SUCCESS";
export const GET_TODAYS_MATCHES_FAILURE = "GET_TODAYS_MATCHES_FAILURE";